exclude = [
    "migrations",
    "venv",
]

line-length = 79
indent-width = 4

[lint]
select = ["ALL"]
ignore = ["D", "ANN", "ARG"]

[format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"
